#!/usr/bin/env bash
# scripts/gen_vapid.sh
# Generate a VAPID keypair for Web Push and write handy env files.
# Prefers Docker (no local installs needed). Falls back to local npx if available.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_ENV_BACKEND="${ROOT_DIR}/.env.vapid"
OUT_ENV_FE="${ROOT_DIR}/frontend/.env.local.example"
OUT_JS_FE="${ROOT_DIR}/frontend/src/vapidPublicKey.js"

SUBJECT_DEFAULT="${VAPID_SUBJECT:-https://taskmanager.sriinfosoft.com}"

have_cmd() { command -v "$1" >/dev/null 2>&1; }

echo "🔐 Generating VAPID keys…"

GEN_CMD=""
if have_cmd docker; then
  GEN_CMD='docker run --rm node:20-alpine sh -lc "npx -y web-push generate-vapid-keys --json"'
elif have_cmd npx; then
  GEN_CMD='npx -y web-push generate-vapid-keys --json'
else
  echo "❌ Neither Docker nor npx is available."
  echo "   Install Docker or Node.js (then npx web-push) and re-run."
  exit 1
fi

RAW_JSON="$(bash -lc "$GEN_CMD")" || {
  echo "❌ Failed to generate keys."
  exit 1
}

# Parse JSON without requiring jq (use jq if present).
if have_cmd jq; then
  PUB="$(printf '%s' "$RAW_JSON" | jq -r '.publicKey')"
  PRV="$(printf '%s' "$RAW_JSON" | jq -r '.privateKey')"
else
  PUB="$(printf '%s' "$RAW_JSON" | sed -n 's/.*"publicKey"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
  PRV="$(printf '%s' "$RAW_JSON" | sed -n 's/.*"privateKey"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
fi

if [[ -z "${PUB:-}" || -z "${PRV:-}" ]]; then
  echo "❌ Could not parse public/private keys from:"
  echo "$RAW_JSON"
  exit 1
fi

mkdir -p "$(dirname "$OUT_ENV_BACKEND")"
cat > "$OUT_ENV_BACKEND" <<EOF
# Backend secrets for Web Push (DO NOT COMMIT THIS FILE PUBLICLY)
VAPID_PUBLIC_KEY=${PUB}
VAPID_PRIVATE_KEY=${PRV}
VAPID_SUBJECT=${SUBJECT_DEFAULT}
EOF

echo "📝 Wrote backend env: $OUT_ENV_BACKEND"

# Frontend helpers (optional if you keep your own config pattern)
mkdir -p "$(dirname "$OUT_ENV_FE")" "$(dirname "$OUT_JS_FE")"

cat > "$OUT_ENV_FE" <<EOF
# Example frontend env for React (copy to .env.local and keep private repo)
REACT_APP_VAPID_PUBLIC_KEY=${PUB}
EOF

# Tiny JS export for convenience (used by your subscribe() code)
cat > "$OUT_JS_FE" <<EOF
// Auto-generated by scripts/gen_vapid.sh
export const VAPID_PUBLIC_KEY = "${PUB}";
EOF

echo "📝 Wrote frontend examples:"
echo "   - $OUT_ENV_FE"
echo "   - $OUT_JS_FE"

cat <<TIP

✅ Keys generated.

Next steps:

1) Backend: load these into your runtime env (compose or ECS):
   - VAPID_PUBLIC_KEY
   - VAPID_PRIVATE_KEY
   - VAPID_SUBJECT  (e.g., ${SUBJECT_DEFAULT})

   In Spring \`application.properties\`:
     vapid.public.key=\${VAPID_PUBLIC_KEY}
     vapid.private.key=\${VAPID_PRIVATE_KEY}
     vapid.subject=\${VAPID_SUBJECT:${SUBJECT_DEFAULT}}

2) Frontend:
   - If you use env: copy frontend/.env.local.example -> frontend/.env.local
   - Or import from src/vapidPublicKey.js:
       import { VAPID_PUBLIC_KEY } from "./vapidPublicKey";

3) Verify:
   docker exec -it <backend-container> printenv | egrep 'VAPID_'
   Then subscribe in a browser and hit:
   curl -X POST "<your-domain>/api/push/test?title=Hello&body=World"

🔒 Keep the PRIVATE key secret (Secrets Manager or environment only). Do not commit it to a public repo.

TIP
